lib/urls.py
#lib/urls.py
from django.urls import path
from . import views

app_name='lib'
urlpatterns = [
    path('',views.index,name='index'),
    path('platformt/', views.platformt, name='platformt'),
    path('detail/',views.detail,name='detail'),
    path('detail_queue/',views.detail_queue,name='detail_queue'),
    path('addBook/',views.addBook,name='addBook'),
    path('delBook/<int:book_id>',views.deleteBook,name='delBook'),
   # path('platformt/',views.platformt,name='platformt'),
]

testDjangoSYL/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('lib/',include('lib.urls')),
    path('admin/', admin.site.urls),
]

lib/models.py
# Database version: 8.0.12
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    pub_house = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    pub_housebig = models.CharField(max_length=200)

    class Meta:
        managed = False
        db_table = 'book'


class Platformtype(models.Model):
    platformtypeid = models.AutoField(db_column='platformTypeID', primary_key=True)  # Field name made lowercase.
    platformtype = models.CharField(db_column='platformType', max_length=32, blank=True,
                                    null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'platformtype'


class Testbeds(models.Model):
    testbedID = models.IntegerField(primary_key=True)
    testbed = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'testbeds'


class Queue(models.Model):
    queueid = models.AutoField(db_column='queueId', primary_key=True)  # Field name made lowercase.
    priority = models.PositiveIntegerField()
    username = models.CharField(db_column='userName', max_length=100)  # Field name made lowercase.
    command = models.CharField(max_length=255)
    description = models.TextField()
    status = models.PositiveIntegerField()
    prefix = models.CharField(max_length=20, blank=True, null=True)
    build = models.CharField(max_length=255, blank=True, null=True)
    tftpip = models.CharField(db_column='tftpIP', max_length=200)  # Field name made lowercase.
    testbed = models.CharField(max_length=35, blank=True, null=True)
    suite = models.CharField(max_length=255, blank=True, null=True)
    dbresults = models.CharField(db_column='dbResults', max_length=1)  # Field name made lowercase.
    runid = models.PositiveIntegerField(db_column='runID')  # Field name made lowercase.
    pidofrun = models.PositiveIntegerField(db_column='pidOfRun')  # Field name made lowercase.
    creationdate = models.DateTimeField(db_column='creationDate')  # Field name made lowercase.
    lastchangedate = models.DateTimeField(db_column='lastChangeDate')  # Field name made lowercase.
    finishdate = models.DateTimeField(db_column='finishDate')  # Field name made lowercase.
    oem = models.CharField(max_length=30, blank=True, null=True)
    loadalcatel = models.CharField(db_column='loadAlcatel', max_length=2, blank=True,
                                   null=True)  # Field name made lowercase.
    userip = models.CharField(db_column='userIP', max_length=255, blank=True, null=True)  # Field name made lowercase.
    removerip = models.CharField(db_column='removerIP', max_length=255, blank=True,
                                 null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'queue'

lib/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Platformtype
from .models import Queue
from .models import Testbeds
import pymysql


def index(request):
    return HttpResponse("Hello,word!")


def detail(request):
    # platformType_list = Platformtype.objects.order_by('-platformTypeID')[:67]
    # context = {'platformType_list' : platformType_list}
    # book_list = Book.objects.order_by('-pub_date')[:5]
    # context = {'book_list': book_list}
    # sql = "SELECT queueId,testbed,build,status,suite,MAX(creationDate),lastChangeDate,finishDate FROM queue GROUP BY testbed ORDER BY testbed"
    sql = "select b.queueId,  b.testbed,b.build, b.`status`,b.creationDate from (SELECT testbed, max(creationDate) as maxdate from queue group by testbed) as a INNER JOIN queue as b on a.testbed = b.testbed and a.maxdate = b.creationDate order by b.testbed "
    queue_list = Queue.objects.raw(sql)
    # queue_list = Queue.objects.raw('select * from queue')
    # queue_list = Queue.objects.order_by('-creationdate')[:100]
    platformt_list = Platformtype.objects.all()
    testbeds_list = Testbeds.objects.all().order_by('testbed')
    # queue_list = Queue.objects.all()[:2]
    # queue_list001 = Queue.objects.order_by('-creationdate').filter(testbed='')
    # queue_list = Queue.objects.order_by('-creationdate')[:100]

    # db = pymysql.connect("localhost", "root", "password", "autoSmoke")
    # # data = cursor1.fetchone()  # 将一条结果放入data
    # # data = cursor1.fetchmany(3)#将3条数据放入data
    # cursor = db.cursor()
    # sql = "SELECT testbed,build,`status`,suite,MAX(creationDate),lastChangeDate,finishDate FROM queue GROUP BY testbed ORDER BY testbed"
    # cursor.execute(sql)
    # rr = cursor.fetchall()
    # pri nt(type(rr))
    # db.close()
    # cursor.close()

    mylist = []
    # a = 1
    #
    # for obj in queue_list[1:]:
    #     tupleList = {}
    #
    #     tupleList["testbedID"] = a
    #     tupleList["testbed"] =obj.testbed[3:]
    #     tupleList["status"] =obj.status
    #     tupleList["build"] =obj.build[3:]
    #     tupleList["suite"] =obj.suite
    #     tupleList["creationdate"] =obj.creationdate
    #     tupleList["finishdate"] =obj.finishdate
    #     mylist.append(tupleList)

    testbed_num = 1
    testbed_busy_sum = 0
    testbed_free_sum = 0

    for a in testbeds_list:
        tupleList = {}
        tupleList["testbedID"] = testbed_num
        tupleList["testbed"] = a.testbed
        for b in queue_list:
            if b.testbed[3:] == a.testbed:
                if b.status < 3:
                    tupleList["status"] = "busy"
                    testbed_busy_sum = testbed_busy_sum + 1
                else:
                    tupleList["status"] = "free"
                    testbed_free_sum = testbed_free_sum + 1
                tupleList["build"] = b.build[3:]
                tupleList["suite"] = b.suite
                tupleList["creationdate"] = b.creationdate
                if b.finishdate == "0000-00-00 00:00:00" and b.status != 0:
                    tupleList["finishdate"] = "unfinished"
                else:
                    tupleList["finishdate"] = b.finishdate
        mylist.append(tupleList)
        testbed_num = testbed_num + 1
        # mylist.sort(key=lambda x:x[1])
        my_sum_busy_list = []
        my_sum_free_list = []
        my_sum_busy_list.append(testbed_busy_sum)
        my_sum_free_list.append(testbed_free_sum)

    # context = {'queue_list': queue_list, 'testbeds_list':testbeds_list,'platform_list': platformt_list}
    context = {'queue_list_my': mylist, 'my_sum_busy_list_dict': my_sum_busy_list,'my_sum_free_list_dict': my_sum_free_list}

    print(type(mylist))

    # print(len(queue_list[5]))
    # print(len(platformt_list))
    # print(len(testbeds_list))
    # print(type(queue_list))
    print(testbeds_list[1].testbed)
    print(testbeds_list[1].testbedID)

    # print(queue_list)

    print(queue_list[1].username)
    # print(queue_list[1].testbed)
    # print(queue_list.index[])
    # print(type(queue_list[2]))
    # print(type(platformt_list))
    # print(platformt_list[0])
    # print(queue_list[0].queueId)
    print(queue_list[1].build)
    print(queue_list[1].status)
    print(queue_list[1].suite)
    print(queue_list[1].testbed)
    # queue_list[0].testbed = queue_list[0].testbed[3:]#切片

    # queue_list[0].username = "asd"
    # print(queue_list[0].userName)
    # print(queue_list[0].creationDate)
    # print(queue_list[0].finishDate)
    # print(queue_list[0].lastChangeDate)
    return render(request, 'lib/detail.html', context)


# return HttpResponseRedirect(rev    erse('lib:detail'))
# return HttpResponse(context)


def addBook(request):
    # if request.method == 'POST':
    #     temp_name = request.POST['name']
    #     temp_author = request.POST['author']
    #     temp_pub_house = request.POST['pub_house']
    #
    # from django.utils import timezone
    # temp_book = Book(name=temp_name, author=temp_author, pub_house=temp_pub_house, pub_date=timezone.now())
    # temp_book.save()
    #
    # return HttpResponseRedirect(reverse('lib:detail'))
    pass


def deleteBook(request, book_id):
    # bookID = book_id
    # Book.objects.filter(id=bookID).delete()
    # return HttpResponseRedirect(reverse('lib:detail'))
    pass


# Create your views here.

def platformt(request):
    # book_list = Book.objects.order_by('-pub_date')[:5]
    # context = {'book_list': book_list}
    # # platformType_list = Platformtype.objects.order_by('-platformTypeID')[:10]
    # # context = {'platformType_list' : platformType_list}
    # return  render(request,'lib/detail.html',context)
    pass


def detail_queue(request):
    # platformType_list = Platformtype.objects.order_by('-platformTypeID')[:67]
    # context = {'platformType_list' : platformType_list}
    # book_list = Book.objects.order_by('-pub_date')[:5]
    # contex = {'book_list': book_list}
    # queue_list = Queue.objects.order_by('-creationDate')
    # context = {'queue_list': queue_list}
    # return render(request, 'lib/detail.html', context)
    pass

templates/lib/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TestBed</title>
    <script src="/static/js/echarts.js"></script>
</head>
<body>
    <div id="main" style="width: 600px;height: 400px;"></div>
    <script type="text/javascript">
        var myChart = echarts.init(document.getElementById('main'));

        var option = {
            title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 20]
            }]
        };
        myChart.setOption(option)

    </script>
<h1>TestBeddddddddddd </h1>
</body>

<body>
<h1>TestBed list </h1>
{#<tr>#}
{#    <td>{{ queue01.queueId }}</td>#}
{#    <td>{{ queue01.userName }}</td>#}
{#</tr>#}
<tr>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td>BUSY_TESTBEDS:</td>
    <td>{{ my_sum_busy_list_dict }}</td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td>FREE_TESTBEDS:</td>
    <td>{{ my_sum_free_list_dict }}</td>
</tr>

<table cellpadding="10px">
    <tr>
        {#        <th>testbedid </th>#}
        <th>ID</th>
        <th>testbed</th>
        <th>status</th>
        <th>build</th>
        {#        <th>testbed </th>#}
        <th>suite</th>
        <th>creationdate</th>
        {#        <th>lastchangedate</th>#}
        <th>finishdate</th>


    </tr>

    {#{% for book in book_list.all %}#}
    {#    <tr>#}
    {#        <td>{{ book.name }}</td>#}
    {#        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>#}
    {#        <td>{{ book.author }}</td>#}
    {#        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>#}
    {#        <td>{{ book.pub_house }}</td>#}
    {#        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>#}
    {#        <td>{{ book.pub_housebig }}</td>#}
    {#        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>#}
    {#        <td>{{ book.pub_date }}</td>#}
    {#        <td><a href="{% url 'lib:delBook' book.id %}">删除</a></td>#}
    {#    </tr>#}
    {#{% endfor %}#}

    {#{% for platformtype01 in platform_list.all %}#}
    {#    <tr>#}
    {#        <td>{{ platformtype01.pltformtypeid }}</td>#}
    {#        <td>{{ platformtype01.platformtype }}</td>#}
    {##}
    {#    </tr>#}
    {##}
    {#{% endfor %}#}
    {#{% for testbeds01 in testbeds_list.all %}#}
    {#    <tr>#}
    {##}
    {#    {% for platformtype01 in platform_list.all %}#}
    {#        <td>{{ testbeds01.testbedID }}</td>#}
    {#        <td>{{ testbeds01.testbed }}</td>#}
    {#        #}
    {#    {% for platformtype01 in context.platform_list %}#}
    {#        <td>{{ context.platformtype01.pltformtypeid }}</td>#}
    {#        <td>{{ context.platformtype01.platformtype }}</td>#}
    {#    {% endfor %}#}
    {#        <td>{{ platformtype01.pltformtypeid }}</td>#}
    {#        <td>{{ platformtype01.platformtype }}</td>#}
    {#    {% endfor %}#}
    {##}
    {##}
    {#    </tr>#}
    {##}
    {#{% endfor %}#}


    {% for queue01 in queue_list_my %}
        <tr>
            {#        <td>{{  }}</td>#}
            {#        <td>{{ queue01.queueid }}</td>#}
            {#        <td>{{ queue01.username }}</td>#}

            <td>{{ queue01.testbedID }}</td>
            <td>{{ queue01.testbed }}</td>
            <td>{{ queue01.status }}</td>
            <td>{{ queue01.build }}</td>
            <td>{{ queue01.suite }}</td>
            <td>{{ queue01.creationdate }}</td>
            {#        <td>{{ queue01.lastchangedate }}</td>#}
            <td>{{ queue01.finishdate }}</td>
        </tr>

    {% endfor %}

</table>
{##}
{#<form action="{% url 'lib:addBook' %}" method="post" name="addBook">#}
{#    {% csrf_token %}#}
{#    <p><span>书名：</span><input type="text" name="name"></p>#}
{#    <p><span>作者：</span><input type="text" name="author"></p>#}
{#    <p><span>出版社：</span><input type="text" name="pub_house"></p>#}
{#    <input type="submit" value="添加">#}
{#</form>#}

</body>
</html>